require("dotenv").config();
const mongoose = require("mongoose");
const Recipe = require("./models/Recipe.model");

mongoose
  .connect(process.env.MONGODB_URI)
  .then(() => console.log("✓ MongoDB connected"))
  .catch((err) => {
    console.error("MongoDB connection error:", err);
    process.exit(1);
  });

const recipes = [
  // ── HIGH PROTEIN ─────────────────────────────────────────────────────────────
  {
    title: "Grilled Chicken & Quinoa Bowl",
    description: "Lean grilled chicken over fluffy quinoa with roasted veg — a complete protein-packed meal.",
    category: "high-protein",
    calories: 480,
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    nutrition: { protein: 52, carbs: 38, fat: 9, fiber: 5 },
    ingredients: [
      { name: "chicken breast", amount: 300, unit: "g" },
      { name: "quinoa (dry)", amount: 150, unit: "g" },
      { name: "cherry tomatoes", amount: 100, unit: "g" },
      { name: "baby spinach", amount: 60, unit: "g" },
      { name: "olive oil", amount: 15, unit: "ml" },
      { name: "lemon juice", amount: 30, unit: "ml" },
      { name: "garlic cloves", amount: 2, unit: "cloves" },
      { name: "dried oregano", amount: 1, unit: "tsp" },
    ],
    instructions: [
      { step: 1, description: "Rinse quinoa and cook in 300 ml water over medium heat for 15 minutes until water is absorbed. Fluff with a fork." },
      { step: 2, description: "Mix olive oil, lemon juice, minced garlic, and oregano. Coat chicken breasts and marinate 10 minutes." },
      { step: 3, description: "Grill chicken on a hot grill pan 6–7 minutes per side until internal temp reaches 75 °C." },
      { step: 4, description: "Halve cherry tomatoes. Slice rested chicken into strips." },
      { step: 5, description: "Divide quinoa between bowls, top with chicken, tomatoes, and spinach. Drizzle remaining marinade." },
    ],
    tags: ["meal-prep", "gluten-free", "high-protein", "low-fat"],
    isActive: true,
  },
  {
    title: "Greek Yogurt Parfait",
    description: "Creamy Greek yogurt layered with fresh berries and crunchy granola — ready in 5 minutes.",
    category: "high-protein",
    calories: 310,
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    nutrition: { protein: 24, carbs: 35, fat: 5, fiber: 4 },
    ingredients: [
      { name: "plain Greek yogurt (0%)", amount: 200, unit: "g" },
      { name: "mixed berries (fresh or frozen)", amount: 120, unit: "g" },
      { name: "granola", amount: 40, unit: "g" },
      { name: "honey", amount: 10, unit: "ml" },
      { name: "chia seeds", amount: 5, unit: "g" },
    ],
    instructions: [
      { step: 1, description: "Spoon half the yogurt into a glass or bowl." },
      { step: 2, description: "Layer half the berries and half the granola on top." },
      { step: 3, description: "Add the remaining yogurt, then the rest of the berries and granola." },
      { step: 4, description: "Drizzle honey over the top and sprinkle chia seeds. Serve immediately." },
    ],
    tags: ["breakfast", "no-cook", "quick", "high-protein"],
    isActive: true,
  },
  {
    title: "Tuna-Stuffed Avocado",
    description: "Protein-rich tuna salad served inside creamy avocado halves — no cooking required.",
    category: "high-protein",
    calories: 390,
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    nutrition: { protein: 34, carbs: 10, fat: 22, fiber: 8 },
    ingredients: [
      { name: "canned tuna in water (drained)", amount: 250, unit: "g" },
      { name: "ripe avocados", amount: 2, unit: "whole" },
      { name: "plain Greek yogurt", amount: 60, unit: "g" },
      { name: "celery stalk", amount: 1, unit: "stalk" },
      { name: "red onion", amount: 30, unit: "g" },
      { name: "lemon juice", amount: 15, unit: "ml" },
      { name: "salt & pepper", amount: 1, unit: "pinch" },
      { name: "fresh dill", amount: 5, unit: "g" },
    ],
    instructions: [
      { step: 1, description: "Halve avocados, remove stones. Scoop out a little flesh to widen the bowl; dice the scooped flesh." },
      { step: 2, description: "Finely dice celery and red onion." },
      { step: 3, description: "Combine tuna, Greek yogurt, celery, red onion, lemon juice, diced avocado, salt, and pepper." },
      { step: 4, description: "Spoon tuna mixture into each avocado half. Garnish with fresh dill and serve." },
    ],
    tags: ["low-carb", "no-cook", "keto-friendly", "lunch"],
    isActive: true,
  },
  {
    title: "Egg-White Spinach Omelette",
    description: "Fluffy egg-white omelette packed with spinach and feta — high protein, very low fat.",
    category: "high-protein",
    calories: 210,
    prepTime: 5,
    cookTime: 8,
    servings: 1,
    nutrition: { protein: 28, carbs: 4, fat: 8, fiber: 1 },
    ingredients: [
      { name: "egg whites", amount: 5, unit: "whole" },
      { name: "baby spinach", amount: 80, unit: "g" },
      { name: "feta cheese", amount: 30, unit: "g" },
      { name: "cherry tomatoes", amount: 50, unit: "g" },
      { name: "olive oil spray", amount: 1, unit: "spray" },
      { name: "black pepper", amount: 1, unit: "pinch" },
    ],
    instructions: [
      { step: 1, description: "Whisk egg whites with a pinch of black pepper until lightly frothy." },
      { step: 2, description: "Spray a non-stick pan with olive oil and place over medium heat." },
      { step: 3, description: "Pour in egg whites; cook 2 minutes until edges set, then add spinach, halved tomatoes, and crumbled feta to one half." },
      { step: 4, description: "Fold the omelette over the filling. Cook 1–2 more minutes, then slide onto a plate." },
    ],
    tags: ["breakfast", "low-fat", "low-carb", "quick"],
    isActive: true,
  },
  {
    title: "Baked Salmon with Broccoli",
    description: "Omega-3 rich salmon fillet with tender roasted broccoli — clean, simple, delicious.",
    category: "high-protein",
    calories: 420,
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    nutrition: { protein: 48, carbs: 12, fat: 18, fiber: 5 },
    ingredients: [
      { name: "salmon fillets", amount: 350, unit: "g" },
      { name: "broccoli florets", amount: 300, unit: "g" },
      { name: "olive oil", amount: 20, unit: "ml" },
      { name: "garlic cloves", amount: 3, unit: "cloves" },
      { name: "lemon", amount: 1, unit: "whole" },
      { name: "fresh dill", amount: 10, unit: "g" },
      { name: "salt & black pepper", amount: 1, unit: "pinch" },
    ],
    instructions: [
      { step: 1, description: "Preheat oven to 200 °C. Toss broccoli with olive oil, minced garlic, salt, and pepper on a baking sheet." },
      { step: 2, description: "Place salmon fillets alongside broccoli. Squeeze half a lemon over salmon; top with dill slices." },
      { step: 3, description: "Bake 18–20 minutes until salmon flakes easily and broccoli is lightly charred." },
      { step: 4, description: "Serve immediately with remaining lemon wedges." },
    ],
    tags: ["gluten-free", "dairy-free", "omega-3", "dinner"],
    isActive: true,
  },
  {
    title: "Turkey & Black Bean Chilli",
    description: "Hearty lean turkey chilli with black beans — great for meal prep and freezes well.",
    category: "high-protein",
    calories: 390,
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    nutrition: { protein: 40, carbs: 32, fat: 7, fiber: 10 },
    ingredients: [
      { name: "lean turkey mince", amount: 500, unit: "g" },
      { name: "canned black beans (drained)", amount: 400, unit: "g" },
      { name: "canned diced tomatoes", amount: 400, unit: "g" },
      { name: "red onion", amount: 1, unit: "whole" },
      { name: "red bell pepper", amount: 1, unit: "whole" },
      { name: "garlic cloves", amount: 4, unit: "cloves" },
      { name: "chilli powder", amount: 1, unit: "tbsp" },
      { name: "cumin", amount: 1, unit: "tsp" },
      { name: "olive oil", amount: 15, unit: "ml" },
    ],
    instructions: [
      { step: 1, description: "Dice onion, pepper, and mince garlic. Sauté in olive oil over medium heat for 5 minutes." },
      { step: 2, description: "Add turkey mince and cook 8 minutes, breaking it up until browned." },
      { step: 3, description: "Stir in chilli powder and cumin; cook 1 minute until fragrant." },
      { step: 4, description: "Add diced tomatoes and black beans. Simmer 20 minutes, stirring occasionally." },
      { step: 5, description: "Season to taste. Serve with lime wedges and optional Greek yogurt." },
    ],
    tags: ["meal-prep", "freezer-friendly", "high-fiber", "dinner"],
    isActive: true,
  },
  {
    title: "Cottage Cheese Pancakes",
    description: "Fluffy, protein-dense pancakes made with cottage cheese — a smart breakfast swap.",
    category: "high-protein",
    calories: 280,
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    nutrition: { protein: 26, carbs: 22, fat: 8, fiber: 1 },
    ingredients: [
      { name: "low-fat cottage cheese", amount: 200, unit: "g" },
      { name: "eggs", amount: 2, unit: "whole" },
      { name: "rolled oats", amount: 50, unit: "g" },
      { name: "vanilla extract", amount: 1, unit: "tsp" },
      { name: "baking powder", amount: 0.5, unit: "tsp" },
      { name: "coconut oil", amount: 10, unit: "ml" },
    ],
    instructions: [
      { step: 1, description: "Blend cottage cheese, eggs, oats, vanilla, and baking powder until smooth." },
      { step: 2, description: "Heat coconut oil in a non-stick pan over medium-low heat." },
      { step: 3, description: "Pour small circles of batter (about 3 tbsp each). Cook 2–3 minutes until bubbles form, then flip." },
      { step: 4, description: "Cook 1–2 more minutes. Serve with fresh berries and a drizzle of honey." },
    ],
    tags: ["breakfast", "gluten-free-option", "quick", "high-protein"],
    isActive: true,
  },
  {
    title: "Beef & Lentil Stuffed Peppers",
    description: "Colourful bell peppers filled with seasoned beef and red lentils — protein and iron in one.",
    category: "high-protein",
    calories: 440,
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    nutrition: { protein: 38, carbs: 34, fat: 12, fiber: 9 },
    ingredients: [
      { name: "large bell peppers (mixed colours)", amount: 4, unit: "whole" },
      { name: "lean beef mince", amount: 350, unit: "g" },
      { name: "red lentils (dry)", amount: 100, unit: "g" },
      { name: "canned diced tomatoes", amount: 200, unit: "g" },
      { name: "onion", amount: 1, unit: "whole" },
      { name: "garlic cloves", amount: 3, unit: "cloves" },
      { name: "paprika", amount: 1, unit: "tsp" },
      { name: "cumin", amount: 0.5, unit: "tsp" },
      { name: "grated cheddar", amount: 40, unit: "g" },
    ],
    instructions: [
      { step: 1, description: "Preheat oven to 190 °C. Cook lentils in salted water for 15 minutes; drain." },
      { step: 2, description: "Cut tops off peppers and remove seeds. Brush lightly with oil and stand in a baking dish." },
      { step: 3, description: "Sauté diced onion and garlic until soft. Add beef mince and cook until browned." },
      { step: 4, description: "Stir in lentils, tomatoes, paprika, and cumin. Simmer 5 minutes; season to taste." },
      { step: 5, description: "Fill peppers with the beef-lentil mixture. Top with cheddar. Bake 25 minutes until peppers are tender." },
    ],
    tags: ["meal-prep", "high-iron", "dinner", "gluten-free"],
    isActive: true,
  },

  // ── HIGH CARB ────────────────────────────────────────────────────────────────
  {
    title: "Banana Oat Power Bowl",
    description: "Warm oatmeal with banana, nut butter, and seeds — the perfect slow-release energy breakfast.",
    category: "high-carb",
    calories: 460,
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    nutrition: { protein: 14, carbs: 72, fat: 12, fiber: 9 },
    ingredients: [
      { name: "rolled oats", amount: 80, unit: "g" },
      { name: "semi-skimmed milk", amount: 250, unit: "ml" },
      { name: "banana", amount: 1, unit: "whole" },
      { name: "almond butter", amount: 15, unit: "g" },
      { name: "mixed seeds (chia, flax, pumpkin)", amount: 10, unit: "g" },
      { name: "cinnamon", amount: 0.5, unit: "tsp" },
      { name: "honey", amount: 10, unit: "ml" },
    ],
    instructions: [
      { step: 1, description: "Combine oats and milk in a saucepan over medium heat. Cook 5–7 minutes, stirring often, until thick." },
      { step: 2, description: "Stir in cinnamon and pour into a bowl." },
      { step: 3, description: "Slice banana and arrange on top. Add a dollop of almond butter." },
      { step: 4, description: "Scatter seeds and drizzle honey to finish." },
    ],
    tags: ["breakfast", "vegan-option", "energy", "meal-prep"],
    isActive: true,
  },
  {
    title: "Sweet Potato & Black Bean Tacos",
    description: "Roasted sweet potato and spiced black beans in warm tortillas — vibrant and filling.",
    category: "high-carb",
    calories: 520,
    prepTime: 15,
    cookTime: 30,
    servings: 3,
    nutrition: { protein: 16, carbs: 82, fat: 9, fiber: 14 },
    ingredients: [
      { name: "sweet potatoes", amount: 500, unit: "g" },
      { name: "canned black beans (drained)", amount: 400, unit: "g" },
      { name: "small corn tortillas", amount: 6, unit: "whole" },
      { name: "red cabbage (shredded)", amount: 100, unit: "g" },
      { name: "avocado", amount: 1, unit: "whole" },
      { name: "lime", amount: 1, unit: "whole" },
      { name: "smoked paprika", amount: 1, unit: "tsp" },
      { name: "cumin", amount: 0.5, unit: "tsp" },
      { name: "olive oil", amount: 20, unit: "ml" },
      { name: "fresh coriander", amount: 15, unit: "g" },
    ],
    instructions: [
      { step: 1, description: "Preheat oven to 200 °C. Cube sweet potatoes, toss with olive oil, paprika, and cumin. Roast 25 minutes." },
      { step: 2, description: "Warm black beans in a pan with a pinch of cumin and salt." },
      { step: 3, description: "Warm tortillas in a dry pan 30 seconds each side." },
      { step: 4, description: "Mash avocado with lime juice and salt." },
      { step: 5, description: "Fill tortillas with sweet potato, beans, cabbage, avocado mash, and coriander." },
    ],
    tags: ["vegan", "plant-based", "dinner", "gluten-free-option"],
    isActive: true,
  },
  {
    title: "Pasta Primavera",
    description: "Whole-wheat pasta tossed with seasonal vegetables in a light garlic-olive oil sauce.",
    category: "high-carb",
    calories: 490,
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    nutrition: { protein: 17, carbs: 78, fat: 11, fiber: 10 },
    ingredients: [
      { name: "whole-wheat penne", amount: 180, unit: "g" },
      { name: "courgette", amount: 1, unit: "whole" },
      { name: "cherry tomatoes", amount: 150, unit: "g" },
      { name: "red bell pepper", amount: 1, unit: "whole" },
      { name: "garlic cloves", amount: 3, unit: "cloves" },
      { name: "olive oil", amount: 25, unit: "ml" },
      { name: "parmesan (grated)", amount: 30, unit: "g" },
      { name: "fresh basil", amount: 10, unit: "g" },
      { name: "lemon zest", amount: 1, unit: "tsp" },
    ],
    instructions: [
      { step: 1, description: "Cook pasta in salted boiling water until al dente (save 100 ml pasta water). Drain." },
      { step: 2, description: "Dice courgette and pepper. Halve tomatoes. Mince garlic." },
      { step: 3, description: "Sauté garlic in olive oil 1 minute. Add courgette and pepper; cook 5 minutes." },
      { step: 4, description: "Add tomatoes and cook 3 minutes until softened." },
      { step: 5, description: "Toss in pasta with a splash of pasta water. Top with parmesan, basil, and lemon zest." },
    ],
    tags: ["vegetarian", "dinner", "high-fiber", "italian"],
    isActive: true,
  },
  {
    title: "Brown Rice Veggie Stir-Fry",
    description: "Colourful stir-fried vegetables over nutty brown rice with a savoury soy-ginger sauce.",
    category: "high-carb",
    calories: 430,
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    nutrition: { protein: 12, carbs: 70, fat: 8, fiber: 7 },
    ingredients: [
      { name: "brown rice (dry)", amount: 160, unit: "g" },
      { name: "broccoli florets", amount: 150, unit: "g" },
      { name: "snap peas", amount: 100, unit: "g" },
      { name: "carrot", amount: 1, unit: "whole" },
      { name: "spring onions", amount: 3, unit: "whole" },
      { name: "low-sodium soy sauce", amount: 30, unit: "ml" },
      { name: "fresh ginger (grated)", amount: 1, unit: "tsp" },
      { name: "sesame oil", amount: 10, unit: "ml" },
      { name: "garlic cloves", amount: 2, unit: "cloves" },
      { name: "sesame seeds", amount: 5, unit: "g" },
    ],
    instructions: [
      { step: 1, description: "Cook brown rice according to packet instructions." },
      { step: 2, description: "Julienne carrot; slice spring onions. Mix soy sauce, ginger, and garlic." },
      { step: 3, description: "Heat sesame oil in a wok over high heat. Stir-fry broccoli and carrot 3 minutes." },
      { step: 4, description: "Add snap peas and spring onions; cook 2 minutes. Pour sauce over and toss." },
      { step: 5, description: "Serve over brown rice, scattered with sesame seeds." },
    ],
    tags: ["vegan", "meal-prep", "asian", "quick"],
    isActive: true,
  },
  {
    title: "Whole-Wheat Banana Muffins",
    description: "Naturally sweetened banana muffins with oats — a satisfying pre- or post-workout snack.",
    category: "high-carb",
    calories: 220,
    prepTime: 10,
    cookTime: 22,
    servings: 6,
    nutrition: { protein: 6, carbs: 38, fat: 5, fiber: 4 },
    ingredients: [
      { name: "ripe bananas", amount: 3, unit: "whole" },
      { name: "whole-wheat flour", amount: 150, unit: "g" },
      { name: "rolled oats", amount: 50, unit: "g" },
      { name: "eggs", amount: 2, unit: "whole" },
      { name: "Greek yogurt", amount: 80, unit: "g" },
      { name: "baking powder", amount: 1, unit: "tsp" },
      { name: "cinnamon", amount: 1, unit: "tsp" },
      { name: "vanilla extract", amount: 1, unit: "tsp" },
    ],
    instructions: [
      { step: 1, description: "Preheat oven to 180 °C. Line a 6-cup muffin tin." },
      { step: 2, description: "Mash bananas well in a large bowl. Whisk in eggs, yogurt, and vanilla." },
      { step: 3, description: "Fold in flour, oats, baking powder, and cinnamon until just combined." },
      { step: 4, description: "Divide batter into muffin cups. Top with a few oat flakes if desired." },
      { step: 5, description: "Bake 20–22 minutes until a skewer comes out clean. Cool on a rack." },
    ],
    tags: ["snack", "meal-prep", "freezer-friendly", "vegetarian"],
    isActive: true,
  },
  {
    title: "Chickpea & Veg Curry with Rice",
    description: "Warming chickpea curry with coconut milk and fragrant spices — rich, plant-based comfort food.",
    category: "high-carb",
    calories: 540,
    prepTime: 10,
    cookTime: 30,
    servings: 3,
    nutrition: { protein: 18, carbs: 80, fat: 12, fiber: 12 },
    ingredients: [
      { name: "canned chickpeas (drained)", amount: 400, unit: "g" },
      { name: "basmati rice (dry)", amount: 200, unit: "g" },
      { name: "canned coconut milk (light)", amount: 200, unit: "ml" },
      { name: "canned diced tomatoes", amount: 400, unit: "g" },
      { name: "onion", amount: 1, unit: "whole" },
      { name: "garlic cloves", amount: 3, unit: "cloves" },
      { name: "fresh ginger", amount: 1, unit: "tbsp" },
      { name: "curry powder", amount: 2, unit: "tbsp" },
      { name: "baby spinach", amount: 80, unit: "g" },
      { name: "olive oil", amount: 15, unit: "ml" },
    ],
    instructions: [
      { step: 1, description: "Cook basmati rice according to packet instructions." },
      { step: 2, description: "Sauté diced onion in olive oil 5 minutes. Add garlic, ginger, and curry powder; cook 2 minutes." },
      { step: 3, description: "Add tomatoes and coconut milk. Bring to a simmer." },
      { step: 4, description: "Add chickpeas and simmer 15 minutes until sauce thickens." },
      { step: 5, description: "Stir in spinach until wilted. Serve over basmati rice." },
    ],
    tags: ["vegan", "dairy-free", "gluten-free", "high-fiber"],
    isActive: true,
  },
  {
    title: "Red Lentil Soup",
    description: "Thick, comforting red lentil soup with cumin and paprika — ready in under 40 minutes.",
    category: "high-carb",
    calories: 360,
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    nutrition: { protein: 20, carbs: 58, fat: 4, fiber: 14 },
    ingredients: [
      { name: "red lentils (dry)", amount: 300, unit: "g" },
      { name: "onion", amount: 1, unit: "whole" },
      { name: "carrot", amount: 2, unit: "whole" },
      { name: "garlic cloves", amount: 4, unit: "cloves" },
      { name: "vegetable stock", amount: 1200, unit: "ml" },
      { name: "cumin seeds", amount: 1, unit: "tsp" },
      { name: "smoked paprika", amount: 1, unit: "tsp" },
      { name: "olive oil", amount: 15, unit: "ml" },
      { name: "lemon juice", amount: 30, unit: "ml" },
    ],
    instructions: [
      { step: 1, description: "Rinse lentils. Dice onion and carrot; mince garlic." },
      { step: 2, description: "Heat olive oil in a large pot. Toast cumin seeds 30 seconds, then add onion and carrot; cook 5 minutes." },
      { step: 3, description: "Add garlic and paprika; cook 1 minute. Add lentils and stock." },
      { step: 4, description: "Bring to a boil, then simmer 25 minutes until lentils are soft." },
      { step: 5, description: "Blend half the soup for a creamy-chunky texture. Stir in lemon juice and season." },
    ],
    tags: ["vegan", "meal-prep", "high-fiber", "budget-friendly"],
    isActive: true,
  },
  {
    title: "Rainbow Quinoa Veggie Bowl",
    description: "Vibrant quinoa bowl with roasted veg, avocado, and a tahini dressing — nutritionally complete.",
    category: "high-carb",
    calories: 500,
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    nutrition: { protein: 16, carbs: 66, fat: 16, fiber: 11 },
    ingredients: [
      { name: "quinoa (dry)", amount: 150, unit: "g" },
      { name: "sweet potato", amount: 200, unit: "g" },
      { name: "red cabbage (shredded)", amount: 80, unit: "g" },
      { name: "cucumber", amount: 1, unit: "whole" },
      { name: "cherry tomatoes", amount: 100, unit: "g" },
      { name: "avocado", amount: 1, unit: "whole" },
      { name: "tahini", amount: 30, unit: "g" },
      { name: "lemon juice", amount: 30, unit: "ml" },
      { name: "olive oil", amount: 15, unit: "ml" },
    ],
    instructions: [
      { step: 1, description: "Cook quinoa in 300 ml water 15 minutes; fluff and season." },
      { step: 2, description: "Cube sweet potato, toss with olive oil, and roast at 200 °C for 20 minutes." },
      { step: 3, description: "Whisk tahini with lemon juice and 2 tbsp water to make dressing." },
      { step: 4, description: "Divide quinoa into bowls. Arrange sweet potato, cabbage, sliced cucumber, tomatoes, and avocado." },
      { step: 5, description: "Drizzle tahini dressing generously over each bowl." },
    ],
    tags: ["vegan", "gluten-free", "meal-prep", "lunch"],
    isActive: true,
  },

  // ── HIGH FAT ─────────────────────────────────────────────────────────────────
  {
    title: "Avocado Toast with Poached Eggs",
    description: "Smashed avocado on sourdough with perfectly poached eggs — a brunch classic done right.",
    category: "high-fat",
    calories: 450,
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    nutrition: { protein: 18, carbs: 32, fat: 28, fiber: 8 },
    ingredients: [
      { name: "ripe avocados", amount: 2, unit: "whole" },
      { name: "thick sourdough slices", amount: 2, unit: "slices" },
      { name: "eggs", amount: 4, unit: "whole" },
      { name: "white wine vinegar", amount: 15, unit: "ml" },
      { name: "lemon juice", amount: 15, unit: "ml" },
      { name: "chilli flakes", amount: 0.5, unit: "tsp" },
      { name: "extra virgin olive oil", amount: 10, unit: "ml" },
      { name: "salt & black pepper", amount: 1, unit: "pinch" },
    ],
    instructions: [
      { step: 1, description: "Toast sourdough until golden and crisp." },
      { step: 2, description: "Mash avocados with lemon juice, salt, pepper, and chilli flakes." },
      { step: 3, description: "Bring a pan of water to a gentle simmer; add vinegar. Swirl and crack eggs in one at a time. Poach 3 minutes." },
      { step: 4, description: "Spread avocado on toast. Top with poached eggs and a drizzle of olive oil." },
    ],
    tags: ["breakfast", "brunch", "vegetarian", "quick"],
    isActive: true,
  },
  {
    title: "Salmon Caesar Salad",
    description: "Pan-seared salmon over crisp romaine with a homemade lightened Caesar dressing.",
    category: "high-fat",
    calories: 510,
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    nutrition: { protein: 42, carbs: 12, fat: 32, fiber: 3 },
    ingredients: [
      { name: "salmon fillets", amount: 300, unit: "g" },
      { name: "romaine lettuce hearts", amount: 2, unit: "whole" },
      { name: "parmesan (shaved)", amount: 30, unit: "g" },
      { name: "olive oil", amount: 20, unit: "ml" },
      { name: "Greek yogurt", amount: 60, unit: "g" },
      { name: "dijon mustard", amount: 5, unit: "g" },
      { name: "garlic clove", amount: 1, unit: "clove" },
      { name: "lemon juice", amount: 20, unit: "ml" },
      { name: "anchovy paste", amount: 5, unit: "g" },
      { name: "wholegrain croutons", amount: 40, unit: "g" },
    ],
    instructions: [
      { step: 1, description: "Whisk yogurt, mustard, minced garlic, anchovy paste, and lemon juice for the dressing." },
      { step: 2, description: "Season salmon. Heat olive oil in a pan; sear salmon skin-side down 4 minutes, flip, cook 3 more minutes." },
      { step: 3, description: "Chop romaine and toss with dressing and most of the parmesan." },
      { step: 4, description: "Plate salad, top with flaked salmon, croutons, and remaining parmesan." },
    ],
    tags: ["low-carb", "omega-3", "lunch", "gluten-free-option"],
    isActive: true,
  },
  {
    title: "Almond Butter Smoothie Bowl",
    description: "Thick, creamy smoothie bowl loaded with healthy fats — keeps you full for hours.",
    category: "high-fat",
    calories: 470,
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    nutrition: { protein: 16, carbs: 38, fat: 28, fiber: 8 },
    ingredients: [
      { name: "frozen banana", amount: 1, unit: "whole" },
      { name: "almond butter", amount: 40, unit: "g" },
      { name: "unsweetened almond milk", amount: 80, unit: "ml" },
      { name: "chia seeds", amount: 10, unit: "g" },
      { name: "granola", amount: 30, unit: "g" },
      { name: "sliced almonds", amount: 15, unit: "g" },
      { name: "fresh berries", amount: 60, unit: "g" },
      { name: "honey", amount: 10, unit: "ml" },
    ],
    instructions: [
      { step: 1, description: "Blend frozen banana, almond butter, and almond milk until very thick and smooth." },
      { step: 2, description: "Pour into a bowl — it should be thick enough to hold toppings." },
      { step: 3, description: "Top with granola, sliced almonds, berries, and chia seeds." },
      { step: 4, description: "Drizzle honey and serve immediately." },
    ],
    tags: ["breakfast", "no-cook", "vegan", "gluten-free"],
    isActive: true,
  },
  {
    title: "Keto Bacon & Egg Cups",
    description: "Crispy bacon-lined cups filled with baked eggs and cheese — zero-carb, max flavour.",
    category: "high-fat",
    calories: 320,
    prepTime: 5,
    cookTime: 18,
    servings: 2,
    nutrition: { protein: 22, carbs: 2, fat: 24, fiber: 0 },
    ingredients: [
      { name: "bacon rashers", amount: 6, unit: "rashers" },
      { name: "eggs", amount: 4, unit: "whole" },
      { name: "cheddar cheese (grated)", amount: 40, unit: "g" },
      { name: "cherry tomatoes", amount: 4, unit: "whole" },
      { name: "fresh chives", amount: 5, unit: "g" },
      { name: "black pepper", amount: 1, unit: "pinch" },
    ],
    instructions: [
      { step: 1, description: "Preheat oven to 190 °C. Line 4 cups of a muffin tin with bacon rashers, overlapping to cover." },
      { step: 2, description: "Add a pinch of cheese to each cup. Crack an egg into each." },
      { step: 3, description: "Halve a tomato and place in each cup. Season with pepper." },
      { step: 4, description: "Bake 15–18 minutes until egg whites are set but yolks still slightly runny." },
      { step: 5, description: "Run a knife around each cup to release. Top with chives and serve." },
    ],
    tags: ["keto", "low-carb", "breakfast", "gluten-free"],
    isActive: true,
  },
  {
    title: "Walnut & Goat Cheese Salad",
    description: "Peppery rocket with candied walnuts, creamy goat cheese, and a balsamic dressing.",
    category: "high-fat",
    calories: 420,
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    nutrition: { protein: 14, carbs: 18, fat: 34, fiber: 4 },
    ingredients: [
      { name: "rocket (arugula)", amount: 120, unit: "g" },
      { name: "walnuts", amount: 60, unit: "g" },
      { name: "soft goat cheese", amount: 80, unit: "g" },
      { name: "pear", amount: 1, unit: "whole" },
      { name: "balsamic vinegar", amount: 20, unit: "ml" },
      { name: "extra virgin olive oil", amount: 25, unit: "ml" },
      { name: "honey", amount: 10, unit: "ml" },
      { name: "dijon mustard", amount: 5, unit: "g" },
    ],
    instructions: [
      { step: 1, description: "Toast walnuts in a dry pan 3–4 minutes; drizzle with honey in the last minute to caramelise. Cool." },
      { step: 2, description: "Whisk balsamic vinegar, olive oil, and mustard into a dressing." },
      { step: 3, description: "Thinly slice pear. Arrange rocket on plates." },
      { step: 4, description: "Top with pear, crumbled goat cheese, and candied walnuts. Drizzle dressing." },
    ],
    tags: ["vegetarian", "low-carb", "starter", "elegant"],
    isActive: true,
  },
  {
    title: "Coconut Chicken Curry",
    description: "Succulent chicken thighs in a rich coconut cream curry — fragrant, indulgent, and dairy-free.",
    category: "high-fat",
    calories: 580,
    prepTime: 15,
    cookTime: 35,
    servings: 3,
    nutrition: { protein: 38, carbs: 14, fat: 40, fiber: 3 },
    ingredients: [
      { name: "boneless chicken thighs", amount: 500, unit: "g" },
      { name: "full-fat coconut cream", amount: 400, unit: "ml" },
      { name: "onion", amount: 1, unit: "whole" },
      { name: "garlic cloves", amount: 4, unit: "cloves" },
      { name: "fresh ginger", amount: 2, unit: "tsp" },
      { name: "Thai red curry paste", amount: 3, unit: "tbsp" },
      { name: "lime", amount: 1, unit: "whole" },
      { name: "fresh coriander", amount: 15, unit: "g" },
      { name: "coconut oil", amount: 15, unit: "ml" },
    ],
    instructions: [
      { step: 1, description: "Cut chicken thighs into chunks. Sauté onion in coconut oil 5 minutes until golden." },
      { step: 2, description: "Add garlic, ginger, and curry paste; cook 2 minutes, stirring constantly." },
      { step: 3, description: "Add chicken and sear 3–4 minutes. Pour in coconut cream." },
      { step: 4, description: "Simmer 25 minutes until chicken is cooked through and sauce is thick." },
      { step: 5, description: "Squeeze lime juice over, scatter coriander. Serve with cauliflower rice for low-carb." },
    ],
    tags: ["dairy-free", "gluten-free", "keto-friendly", "dinner"],
    isActive: true,
  },
  {
    title: "Macadamia-Crusted Tilapia",
    description: "Delicate tilapia fillets crusted with buttery macadamia nuts and a hint of lime.",
    category: "high-fat",
    calories: 440,
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    nutrition: { protein: 36, carbs: 6, fat: 30, fiber: 2 },
    ingredients: [
      { name: "tilapia fillets", amount: 350, unit: "g" },
      { name: "macadamia nuts (finely chopped)", amount: 80, unit: "g" },
      { name: "panko breadcrumbs", amount: 30, unit: "g" },
      { name: "egg", amount: 1, unit: "whole" },
      { name: "lime", amount: 1, unit: "whole" },
      { name: "fresh parsley", amount: 10, unit: "g" },
      { name: "butter", amount: 15, unit: "g" },
      { name: "salt & pepper", amount: 1, unit: "pinch" },
    ],
    instructions: [
      { step: 1, description: "Preheat oven to 200 °C. Mix chopped macadamias, panko, parsley, and lime zest on a plate." },
      { step: 2, description: "Beat egg in a shallow bowl. Season tilapia fillets." },
      { step: 3, description: "Dip each fillet in egg, then press firmly into the nut crust on both sides." },
      { step: 4, description: "Melt butter in an oven-proof pan. Sear fillets 2 minutes per side." },
      { step: 5, description: "Transfer pan to oven; bake 8 minutes until crust is golden. Serve with lime wedges." },
    ],
    tags: ["gluten-free-option", "low-carb", "dinner", "elegant"],
    isActive: true,
  },
  {
    title: "Pesto Zoodles with Grilled Chicken",
    description: "Courgette noodles tossed in fresh basil pesto with sliced grilled chicken — light yet satisfying.",
    category: "high-fat",
    calories: 480,
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    nutrition: { protein: 40, carbs: 10, fat: 32, fiber: 4 },
    ingredients: [
      { name: "large courgettes", amount: 3, unit: "whole" },
      { name: "chicken breast", amount: 300, unit: "g" },
      { name: "fresh basil", amount: 40, unit: "g" },
      { name: "pine nuts", amount: 40, unit: "g" },
      { name: "parmesan (grated)", amount: 40, unit: "g" },
      { name: "extra virgin olive oil", amount: 60, unit: "ml" },
      { name: "garlic cloves", amount: 2, unit: "cloves" },
      { name: "lemon juice", amount: 15, unit: "ml" },
    ],
    instructions: [
      { step: 1, description: "Blend basil, pine nuts, parmesan, garlic, lemon juice, and olive oil into a smooth pesto." },
      { step: 2, description: "Season and grill chicken breast 6–7 minutes per side; rest 5 minutes then slice." },
      { step: 3, description: "Spiralise courgettes into noodles (or use a peeler for ribbons)." },
      { step: 4, description: "Briefly sauté zoodles in a hot pan 1–2 minutes — just to warm, keeping them firm." },
      { step: 5, description: "Toss zoodles with pesto. Plate and top with sliced chicken and extra parmesan." },
    ],
    tags: ["low-carb", "keto-friendly", "gluten-free", "dinner"],
    isActive: true,
  },
];

const seedRecipes = async () => {
  try {
    const existing = await Recipe.countDocuments();
    if (existing > 0) {
      console.log(`⚠️  ${existing} recipes already exist. Dropping and re-seeding...`);
      await Recipe.deleteMany({});
    }

    const inserted = await Recipe.insertMany(recipes);
    console.log(`✓ Seeded ${inserted.length} recipes (${inserted.length / 8} per category)`);
  } catch (err) {
    console.error("Seed error:", err.message);
  } finally {
    await mongoose.connection.close();
    console.log("✓ MongoDB connection closed");
  }
};

seedRecipes();
