import {
  Heart,
  Footprints,
  Flame,
  Moon,
  Droplets,
  Wind,
  Ruler,
  Weight,
} from "lucide-react";

export const METRIC_CONFIG = {
  heartRate: {
    label: "Heart Rate",
    unit: "bpm",
    icon: Heart,
    color: "hsl(0, 80%, 55%)",
    goal: null,
    format: (v) => Math.round(v),
  },
  steps: {
    label: "Steps",
    unit: "steps",
    icon: Footprints,
    color: "hsl(217, 91%, 60%)",
    goal: 10000,
    format: (v) => v?.toLocaleString?.() ?? v,
  },
  calories: {
    label: "Calories",
    unit: "kcal",
    icon: Flame,
    color: "hsl(25, 95%, 53%)",
    goal: 2000,
    format: (v) => Math.round(v)?.toLocaleString?.(),
  },
  sleep: {
    label: "Sleep",
    unit: "hrs",
    icon: Moon,
    color: "hsl(263, 70%, 58%)",
    goal: 8,
    format: (v) => Number(v).toFixed(1),
  },
  bloodPressure: {
    label: "Blood Pressure",
    unit: "mmHg",
    icon: Droplets,
    color: "hsl(340, 82%, 52%)",
    goal: null,
    format: (v) => (typeof v === "object" ? `${v.systolic}/${v.diastolic}` : v),
  },
  oxygenSaturation: {
    label: "SpO2",
    unit: "%",
    icon: Wind,
    color: "hsl(172, 66%, 50%)",
    goal: null,
    format: (v) => Math.round(v),
  },
  distance: {
    label: "Distance",
    unit: "km",
    icon: Ruler,
    color: "hsl(142, 71%, 45%)",
    goal: 5,
    format: (v) => Number(v).toFixed(1),
  },
  bloodGlucose: {
    label: "Blood Glucose",
    unit: "mg/dL",
    icon: Droplets,
    color: "hsl(48, 96%, 53%)",
    goal: null,
    format: (v) => Math.round(v),
  },
  weight: {
    label: "Weight",
    unit: "kg",
    icon: Weight,
    color: "hsl(200, 65%, 50%)",
    goal: null,
    format: (v) => Number(v).toFixed(1),
  },
};
